### ISSUE TITLE
no new gas or infuser type

### ISSUE THREAD

**Issue by Koldra** [Frinn38/MekaJS#1]
I have copy and paste your examples but i don't have any new gas in game that are the lines in the kubejs startup_script

onEvent('infuser_type.registry', event => {

    event.create("clay_ball").color(9344921).texture("kubejs:infuser_types/clay.png")

})

onEvent('gas.registry', event => {
	
     event.create("clay_ball").color(9344921).texture("kubejs:infuser_types/clay.png")
	 
})

**Comment by Frinn38** [comment]
Look like something changed in KubJS that broke this addon, I updated KubeJS dependency to latest version and fixed the errors.
The new file on curseforge (MekaJS-1.16.5-1.2.0) should work

**Comment by Frinn38** [comment]
just tested with 1.2.0 and I confirm it works, also if you use `.texture()` be sure to have a texture (.png) file at this location, if you don't, just don't use `.texture()` and the gas or infuser type will just use the default texture with the color you specified.
