### ISSUE TITLE
File lang not recognized

### ISSUE THREAD

**Issue by andronikuspailan** [Frinn38/MekaJS#2]
Following how to add lang,but it still gives me gas.kubejs.(your gas name) :

my startup_scripts:
onEvent('infuser_type.registry', event => {
	event.create("quartz_infuser").color(9737364)
})

onEvent('gas.registry', event => {
	event.create("quartz_infuser").color(9737364)
})

my lang files (use name en_us.lang):
gas.kubejs.quartz_infuser=Quartz Gas

my lang files (use name en_us.json):
"gas.kubejs.quartz_infuser"="Quartz Gas"

note:
if en_us.lang can't do it,then i change to en_us.json. but it still same for me. sorry bad english :(

**Comment by Frinn38** [comment]
in 1.16 lang files are now json so it's `en_us.json`
be sure that the file is placed in `/kubejs/assets/kubejs/lang/en_us.json`
the file content should be a json object so : 
```json
{
    "gas.kubejs.quartz_infuser":"Quartz Gas"
}
```

**Comment by andronikuspailan** [comment]
how i added specified item for my new gasses? i want to add quartz to new infuse type...

**Comment by Frinn38** [comment]
If you want to add a recipe for your gas or use your gas in a recipe simply use "kubejs:gas_id" so "kubejs:quartz_infuser"  in the recipe json.
